[package]
name = "plotly_kaleido"
version = "0.2.0"
description = "Additional output format support for plotly using Kaleido"
authors = ["Ioannis Giagkiozis <i.giagkiozis@gmail.com>"]
license = "MIT"
readme = "README.md"
workspace = ".."
homepage = "https://github.com/igiagkiozis/plotly"
documentation = "https://docs.rs/plotly_kaleido"
repository = "https://github.com/igiagkiozis/plotly"
edition = "2018"
keywords = ["plot", "chart", "plotly", "ndarray"]

exclude = [
    "target/*",
    "kaleido/*",
    "examples/*"
]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
base64 = "0.12.3"
thiserror = "1.0.23"

[dev-dependencies]
zip = "0.5.6"

[build-dependencies]
zip = "0.5.6"